import type { EnemyConfig } from '../types';

export const ENEMIES: Record<string, EnemyConfig> = {
  'shield-scout': { id: 'shield-scout', actionNames: ['莢膜護衣', '菌仔撞撞'], name: '莢膜菌盾仔', type: 'normal', kind: 'capsule', maxHp: 360, attackPattern: [{ type: 'shield', amount: 24 }, { type: 'attack', amount: 10 }], asset: 'capsule', tagline: '把透明莢膜穿成防護衣的小菌，先破盾再反擊' },
  'shield-slime': { id: 'shield-slime', actionNames: ['厚膜泡泡', '泡泡彈射', '薄膜補補', '菌團衝撞'], name: '生物膜泡泡菌', type: 'normal', kind: 'biofilm', maxHp: 430, attackPattern: [{ type: 'shield', amount: 36 }, { type: 'attack', amount: 12 }, { type: 'shield', amount: 16 }, { type: 'attack', amount: 8 }], asset: 'biofilm', tagline: '躲在泡泡菌膜裡，厚盾與薄盾交替登場' },
  'stone-guard': { id: 'stone-guard', actionNames: ['結晶硬殼', '咔咔封格', '碎石彈跳'], name: '結石咔咔怪', type: 'normal', kind: 'crystal', maxHp: 490, attackPattern: [{ type: 'shield', amount: 28 }, { type: 'stone', amount: 1 }, { type: 'attack', amount: 14 }], asset: 'crystal', tagline: '愛把水母包成小石頭，附近消除一次即可解除' },
  'shell-warden': { id: 'shell-warden', actionNames: ['菌膜堡壘', '菌王衝撞', '菌團封路'], name: '耐藥堡壘菌王', type: 'boss', kind: 'superbug', maxHp: 820, attackPattern: [{ type: 'shield', amount: 32 }, { type: 'attack', amount: 14 }, { type: 'blocker', amount: 1 }], bossSpecial: { title: '菌膜裝甲衝撞', effectText: '攻擊 20，並獲得 24 點護盾', actions: [{ type: 'attack', amount: 20 }, { type: 'shield', amount: 24 }], initialDelay: 2, cooldown: 2 }, asset: 'superbug', tagline: '把菌膜堆成堡壘，連鎖能打斷裝甲衝撞' },
  'mist-sprite': { id: 'mist-sprite', actionNames: ['噗噗鼻霧', '紅鼻撞擊'], name: '鼻炎噗噗怪', type: 'normal', kind: 'rhinitis', maxHp: 380, attackPattern: [{ type: 'fog', amount: 2 }, { type: 'attack', amount: 10 }], asset: 'rhinitis', tagline: '紅鼻子一抖就噴霧，COO 能清除迷霧' },
  'forest-slime': { id: 'forest-slime', actionNames: ['鼻竇噴霧', '鼻涕彈射', '黏黏拖尾', '軟糖衝撞'], name: '鼻竇黏黏怪', type: 'normal', kind: 'mucus', maxHp: 430, attackPattern: [{ type: 'fog', amount: 3 }, { type: 'attack', amount: 12 }, { type: 'slime', amount: 1 }, { type: 'attack', amount: 8 }], asset: 'mucus', tagline: '拖著鼻涕尾巴到處黏，先清理黏液再串連鎖' },
  'vine-guard': { id: 'vine-guard', actionNames: ['呼呼氣霧', '氣管纏繞', '咳咳震波', '呼呼氣霧'], name: '支氣管纏纏怪', type: 'normal', kind: 'bronchus', maxHp: 500, attackPattern: [{ type: 'fog', amount: 2 }, { type: 'blocker', amount: 1 }, { type: 'attack', amount: 14 }, { type: 'fog', amount: 2 }], asset: 'bronchus', tagline: '氣管觸手纏住盤面，淨化迷霧與鎖定' },
  'forest-beast': { id: 'forest-beast', actionNames: ['棘刺霧旋', '病毒俯衝', '黏液飛沫', '噴嚏突襲'], name: '流感風暴病毒', type: 'boss', kind: 'influenza', maxHp: 860, attackPattern: [{ type: 'fog', amount: 3 }, { type: 'attack', amount: 15 }, { type: 'slime', amount: 1 }, { type: 'attack', amount: 10 }], bossSpecial: { title: '噴嚏風暴', effectText: '攻擊 20，並讓 3 格起霧', actions: [{ type: 'attack', amount: 20 }, { type: 'fog', amount: 3 }], initialDelay: 2, cooldown: 2 }, asset: 'influenza', tagline: '旋轉棘刺捲起噴嚏風暴，兩波消除或 QCC 可打斷' },
  bacteria: { id: 'bacteria', name: '細菌怪小隊', type: 'normal', kind: 'bacteria', maxHp: 150, attackPattern: [{ type: 'attack', amount: 8 }, { type: 'blocker', amount: 1 }], asset: 'bacteria', tagline: '吵鬧黏人的小怪群' },
  cold: { id: 'cold', name: '感冒噴嚏雲', type: 'normal', kind: 'cold', maxHp: 185, attackPattern: [{ type: 'fog', amount: 2 }, { type: 'attack', amount: 10 }], asset: 'cold', tagline: '呼——霧氣來了！' },
  sleepy: { id: 'sleepy', name: '疲勞哈欠怪', type: 'normal', kind: 'sleepy', maxHp: 210, attackPattern: [{ type: 'attack', amount: 6 }, { type: 'attack', amount: 10 }], actionNames: ['哈欠衝擊', '疲勞撞撞'], asset: 'sleepy', tagline: '哈欠打得震天響，準備迎接撞撞攻擊！' },
  forgetful: { id: 'forgetful', name: '腦霧健忘怪', type: 'normal', kind: 'forgetful', maxHp: 220, attackPattern: [{ type: 'attack', amount: 6 }, { type: 'attack', amount: 10 }], asset: 'forgetful', tagline: '想起來了，準備出擊！' },
  blur: { id: 'blur', name: '眼睛模糊怪', type: 'boss', kind: 'blur', maxHp: 560, attackPattern: [{ type: 'fog', amount: 3 }, { type: 'attack', amount: 15 }, { type: 'fog', amount: 2 }], bossSpecial: { title: '濃霧震波', effectText: '攻擊 22，並讓 3 格起霧', actions: [{ type: 'attack', amount: 22 }, { type: 'fog', amount: 3 }], initialDelay: 1, cooldown: 2 }, statMultipliers: { Eye: 1.2, Pai: 0.9 }, asset: 'blur', tagline: '濃霧遮不住你的眼力！' },
  'three-high': { id: 'three-high', name: '三高怪', type: 'boss', kind: 'three-high', maxHp: 650, attackPattern: [{ type: 'blocker', amount: 2 }, { type: 'shield', amount: 24 }, { type: 'attack', amount: 17 }], bossSpecial: { title: '三重壓力波', effectText: '攻擊 18、障礙 +2、護盾 +16', actions: [{ type: 'attack', amount: 18 }, { type: 'blocker', amount: 2 }, { type: 'shield', amount: 16 }], initialDelay: 1, cooldown: 1 }, statMultipliers: { Tum: 1.15, Bac: 0.9 }, asset: 'three-high', tagline: '三個頭，三種麻煩！' },
  slime: { id: 'slime', name: '痰液黏黏怪', type: 'normal', kind: 'slime', maxHp: 320, attackPattern: [{ type: 'slime', amount: 2 }, { type: 'attack', amount: 12 }], statMultipliers: { Vir: 1.15 }, asset: 'slime', tagline: '黏液格可用鄰近消除解除' },
  joint: { id: 'joint', name: '關節痠痛巨像', type: 'boss', kind: 'joint', maxHp: 740, attackPattern: [{ type: 'stone', amount: 1 }, { type: 'attack', amount: 18 }, { type: 'shield', amount: 20 }], bossSpecial: { title: '巨像重踏', effectText: '攻擊 24，並石化 2 格', actions: [{ type: 'attack', amount: 24 }, { type: 'stone', amount: 2 }], initialDelay: 1, cooldown: 2 }, statMultipliers: { Bac: 1.2, Sch: 0.9 }, asset: 'joint', tagline: '擊碎石化格，打破僵局！' },
};
