import type { EnemyConfig } from '../types';

export const ENEMIES: Record<string, EnemyConfig> = {
  'shield-scout': { id: 'shield-scout', name: '甲殼斥候', type: 'normal', kind: 'shell', maxHp: 360, attackPattern: [{ type: 'shield', amount: 24 }, { type: 'attack', amount: 10 }], asset: 'shell', tagline: '累積 KTT 充能，擊穿第一道護盾' },
  'shield-slime': { id: 'shield-slime', name: '泡泡盾怪', type: 'normal', kind: 'slime', maxHp: 430, attackPattern: [{ type: 'shield', amount: 36 }, { type: 'attack', amount: 12 }, { type: 'shield', amount: 16 }, { type: 'attack', amount: 8 }], asset: 'slime', tagline: '厚盾與薄盾交替，抓準爆發時機' },
  'stone-guard': { id: 'stone-guard', name: '石門守衛', type: 'normal', kind: 'joint', maxHp: 490, attackPattern: [{ type: 'shield', amount: 28 }, { type: 'stone', amount: 1 }, { type: 'attack', amount: 14 }], asset: 'joint', tagline: '附近消除一次，就能解除石化' },
  'shell-warden': { id: 'shell-warden', name: '甲殼守衛', type: 'boss', kind: 'shell', maxHp: 820, attackPattern: [{ type: 'shield', amount: 32 }, { type: 'attack', amount: 14 }, { type: 'blocker', amount: 1 }], bossSpecial: { title: '甲殼重擊', effectText: '攻擊 20，並獲得 24 點護盾', actions: [{ type: 'attack', amount: 20 }, { type: 'shield', amount: 24 }], initialDelay: 2, cooldown: 2 }, asset: 'shell', tagline: '先破盾，再用連鎖打斷重擊' },
  'mist-sprite': { id: 'mist-sprite', name: '薄霧精靈', type: 'normal', kind: 'cold', maxHp: 380, attackPattern: [{ type: 'fog', amount: 2 }, { type: 'attack', amount: 10 }], asset: 'cold', tagline: '薄霧持續兩回合，善用 COO 淨化' },
  'forest-slime': { id: 'forest-slime', name: '苔蘚黏液怪', type: 'normal', kind: 'slime', maxHp: 430, attackPattern: [{ type: 'fog', amount: 3 }, { type: 'attack', amount: 12 }, { type: 'slime', amount: 1 }, { type: 'attack', amount: 8 }], asset: 'slime', tagline: '先清理黏液，再串起連鎖' },
  'vine-guard': { id: 'vine-guard', name: '藤蔓守衛', type: 'normal', kind: 'forest', maxHp: 500, attackPattern: [{ type: 'fog', amount: 2 }, { type: 'blocker', amount: 1 }, { type: 'attack', amount: 14 }, { type: 'fog', amount: 2 }], asset: 'forest', tagline: '淨化迷霧與鎖定，保持盤面通暢' },
  'forest-beast': { id: 'forest-beast', name: '霧林巨獸', type: 'boss', kind: 'forest', maxHp: 860, attackPattern: [{ type: 'fog', amount: 3 }, { type: 'attack', amount: 15 }, { type: 'slime', amount: 1 }, { type: 'attack', amount: 10 }], bossSpecial: { title: '霧林咆哮', effectText: '攻擊 20，並讓 3 格起霧', actions: [{ type: 'attack', amount: 20 }, { type: 'fog', amount: 3 }], initialDelay: 2, cooldown: 2 }, asset: 'forest', tagline: '用兩波消除或 QCC 打斷咆哮' },
  bacteria: { id: 'bacteria', name: '細菌怪小隊', type: 'normal', kind: 'bacteria', maxHp: 150, attackPattern: [{ type: 'attack', amount: 8 }, { type: 'blocker', amount: 1 }], asset: 'bacteria', tagline: '吵鬧黏人的小怪群' },
  cold: { id: 'cold', name: '噴嚏雲怪', type: 'normal', kind: 'cold', maxHp: 185, attackPattern: [{ type: 'fog', amount: 2 }, { type: 'attack', amount: 10 }], asset: 'cold', tagline: '呼——霧氣來了！' },
  sleepy: { id: 'sleepy', name: '沒精神怪', type: 'normal', kind: 'sleepy', maxHp: 210, attackPattern: [{ type: 'darken', turns: 1 }, { type: 'attack', amount: 10 }], asset: 'sleepy', tagline: '呵啊……好想睡……' },
  forgetful: { id: 'forgetful', name: '健忘怪', type: 'normal', kind: 'forgetful', maxHp: 220, attackPattern: [{ type: 'attack', amount: 6 }, { type: 'attack', amount: 10 }], asset: 'forgetful', tagline: '想起來了，準備出擊！' },
  blur: { id: 'blur', name: '眼睛模糊怪', type: 'boss', kind: 'blur', maxHp: 560, attackPattern: [{ type: 'fog', amount: 3 }, { type: 'attack', amount: 15 }, { type: 'fog', amount: 2 }], bossSpecial: { title: '濃霧震波', effectText: '攻擊 22，並讓 3 格起霧', actions: [{ type: 'attack', amount: 22 }, { type: 'fog', amount: 3 }], initialDelay: 1, cooldown: 2 }, statMultipliers: { Eye: 1.2, Pai: 0.9 }, asset: 'blur', tagline: '濃霧遮不住你的眼力！' },
  'three-high': { id: 'three-high', name: '三高怪', type: 'boss', kind: 'three-high', maxHp: 650, attackPattern: [{ type: 'blocker', amount: 2 }, { type: 'shield', amount: 24 }, { type: 'attack', amount: 17 }], bossSpecial: { title: '三重壓力波', effectText: '攻擊 18、障礙 +2、護盾 +16', actions: [{ type: 'attack', amount: 18 }, { type: 'blocker', amount: 2 }, { type: 'shield', amount: 16 }], initialDelay: 1, cooldown: 1 }, statMultipliers: { Tum: 1.15, Bac: 0.9 }, asset: 'three-high', tagline: '三個頭，三種麻煩！' },
  slime: { id: 'slime', name: '黏液怪', type: 'normal', kind: 'slime', maxHp: 320, attackPattern: [{ type: 'slime', amount: 2 }, { type: 'attack', amount: 12 }], statMultipliers: { Vir: 1.15 }, asset: 'slime', tagline: '黏液格可用鄰近消除解除' },
  joint: { id: 'joint', name: '關節痠痛巨像', type: 'boss', kind: 'joint', maxHp: 740, attackPattern: [{ type: 'stone', amount: 1 }, { type: 'attack', amount: 18 }, { type: 'shield', amount: 20 }], bossSpecial: { title: '巨像重踏', effectText: '攻擊 24，並石化 2 格', actions: [{ type: 'attack', amount: 24 }, { type: 'stone', amount: 2 }], initialDelay: 1, cooldown: 2 }, statMultipliers: { Bac: 1.2, Sch: 0.9 }, asset: 'joint', tagline: '擊碎石化格，打破僵局！' },
};
